export const label = {
  pan: "PAN",
  gstin: "GSTIN",
  address: "Address",
  phoneNumber: "Tel:",
  invoiceNumber: "Invoice No.",
  invoiceDate: "Date of Invoice",
  placeOfSupply: "Place of Supply",
  reverseCharge: "Reverse Charge",
  placeOfSupply: "Place of Supply",
  po: "PO No",
  poDate: "PO Date",
  contactPerson: "Contact Person",
  contactNumber: "Contact No",
  ref: "REF",
  remark: "Remark",
  vendorCode: "Vendor Code",
  challanDate: "CH Date",
  billTo: "Bill to",
  shipTo: "Ship to",
  consignee: "Consignee",
  customer: {
    email: "E-Mail ID",
    mobile: "Mobile No",
    gstin: "GSTIN / UIN",
    cst: "Company's CST No",
    pan: "Company's PAN",
  },
  orderNumber: "Order No.",
  challanNumber: "Challan No.",
  orderDescription: "Description",
  descriptionTable: {
    sn: "S.N.",
    description: "Description of Goods",
    hsnOrSac: "HSN/SAC",
    uom: "UOM",
    qty: "QTY.",
    rate: "Rate",
    discount: "Discount",
    amount: "Amount",
  },
  cgst: "CGST",
  sgst: "SGST",
  amountInWords: "Amount Chargeable (in words)",
  taxTable: {
    hsnOrSac: "HSN/SAC",
    taxRate: "Tax Rate",
    taxableAmount: "Taxable amt.",
    totalTax: "Total Tax",
  },
  bankTable: {
    bankName: "BANK NAME",
    branch: "BRANCH",
    acNumber: "A/C NO",
    ifsc: "IFSC CODE",
  },
  customerSignature: "Customer's Seal and Signature",
  ownerSignature: "Authorised Signatory",
  total: "total",
  addCgst: "Add: CGST @ 9.00%",
  addSgst: "Add: SGST @ 9.00%",
  grandTotal: "Grand Total ( E.& O.E.)",
  tnc: "Terms & Conditions",
};
